# Generated by Django 3.2 on 2022-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('profiles', '0002_savedeventlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedeventlist',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
