# Generated by Django 3.2 on 2022-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='book_author',
            field=models.CharField(default='Jane Austen', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='month_book',
            field=models.CharField(default='The Club', max_length=200),
        ),
    ]
