# Generated by Django 3.2 on 2022-06-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220625_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
