# Generated by Django 3.2 on 2022-06-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
