# Generated by Django 3.2 on 2022-04-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
