# Generated by Django 3.2 on 2022-06-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
